services:
  db:
    image: mysql:8.0
    container_name: aquamanager_db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-aquamanager}
      MYSQL_USER: ${DB_USER:-aquamanager}
      MYSQL_PASSWORD: ${DB_PASS:-aquamanager}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpass}
    #ports:
    # - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: aquamanager_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-aquamanager}
      DB_PASS: ${DB_PASS:-aquamanager}
      DB_NAME: ${DB_NAME:-aquamanager}

      JWT_SECRET: ${JWT_SECRET:-change_me_at_least_16_chars}
      JWT_EXPIRES: ${JWT_EXPIRES:-1h}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES:-15d}
      CONTACT_TO_EMAIL: ${CONTACT_TO_EMAIL:-aquamanager.contact@gmail.com}
      ANALYTICS_SALT: ${ANALYTICS_SALT:-change_me_long_random_string_32_chars_min}


      NODE_ENV: production
      PORT: 3000

      # ✅ IMPORTANT prod
      TYPEORM_SYNC: "false"
      TYPEORM_LOGGING: "false"

      # ✅ uploads persistants
      UPLOAD_DIR: /data/uploads

      # ✅ EMAIL (Gmail SMTP)
      APP_URL: ${APP_URL:-https://aquamanager.fr}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_SECURE: ${SMTP_SECURE:-true}
      SMTP_USER: ${SMTP_USER:-aquamanager.contact@gmail.com}
      SMTP_PASS: ${SMTP_PASS:-ishdizrethtfbsoy}
      EMAIL_FROM: ${EMAIL_FROM:-AquaManager <aquamanager.contact@gmail.com>}

    ports:
      - "3000:3000"
    volumes:
      # ⚠️ Sur le VPS, crée /opt/aquamanager/uploads
      - /opt/aquamanager/uploads:/data/uploads
      - /opt/aquamanager/tmp:/app/tmp

  frontend:
    build:
      context: ./front_end/web
      dockerfile: Dockerfile
    container_name: aquamanager_front
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front_end/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: aquamanager_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt

volumes:
  db_data:
  certbot_www:
  certbot_certs:
