name: CI - Cypress (frontend)

on:
  push:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: |
          cd front_end/web
          npm install

      - name: Build Angular app
        run: |
          cd front_end/web
          npm run build

      - name: Start HTTP server on dist (background)
        run: |
          cd front_end/web
          npx http-server ./dist/web/browser -p 4200 &

      - name: Run Cypress tests
        run: |
          cd front_end/web
          npx cypress run
